
version: "2.1"
services:

    web-redis:
      container_name: web-redis
      image: redis:latest
      ports:
        - "6379:6379"

    web-mysql:
      image: mysql:latest
      container_name: web-mysql
      volumes:
          - ./mysql:/var/lib/mysql-files
          - ./mysql:/docker-entrypoint-initdb.d
      ports:
       - "3306:3306"
      tty: true
      environment:
        - MYSQL_ROOT_PASSWORD=root

    web-apache:
      image: sharnw/webcore-docker-apache
      container_name: web-apache
      stdin_open: true
      tty: true
      links:
        - "web-redis"
        - "web-mysql"
      volumes:
        - ./web:/var/www/html
        - ./vhost:/etc/apache2/sites-enabled
        - ./cert:/etc/certs
        - ./log:/var/log/apache2
        - ./composer:/var/www/.composer
        - ./npm:/var/www/.npm
      ports:
       - "80:80"
       - "443:443"